---
title: "R Notebook"
output: html_notebook
---

```{r}
library(cowplot)
library(lme4)
library(lmerTest)
library(pbkrtest)
```


## RCBD
```{r}
set.seed(5)
nG = 10
data = expand.grid(Block = factor(1:nG),Insecticide = c('A','B'),Pot = 1:2, Plant = 1:2)
G = rnorm(nG,0,5)
GT = rnorm(nG*2,0,3)
Insecticide = c(0,5)
# GT[1] = 50
data$Biomass = 40 + Insecticide[data$Insecticide] + G[data$Block] + GT[interaction(data$Block,data$Insecticide)] + rnorm(nrow(data),0,4)
# data[order(data$Block,data$Insecticide,data$Pot,data$Plant),]
data$Pot = interaction(data$Pot,data$Insecticide,data$Block)
# data
```
```{r}
ggplot(data,aes(x=Block,y=Biomass)) + geom_boxplot(aes(color = Insecticide),position = position_dodge(width = .25))
# ggplot(data,aes(x=Block,y=Biomass)) + geom_point(aes(color = Insecticide),position = position_dodge(width = .25)) #+ stat_summary(aes(color=Insecticide,group=Insecticide),fun.y = mean,geom='line',size=3)
```

```{r}
lme1 = lmer(Biomass~Block+Insecticide+(1|Block:Insecticide) + (1|Pot),data)
anova(lme1,ddf='K')
# lme1 = lmer(Biomass~(1|Block)+Insecticide+(1|Block:Insecticide) + (1|Pot),data)
# anova(lme1,ddf='k')
# VarCorr(lme1)
```

```{r}
library(emmeans)
# summary(emmeans(lme1,pairwise~Insecticide,mode='k')$contrast,infer=T)
lme2 = lmer(Biomass~Block*Insecticide + (1|Pot),data)
anova(lme2,ddf='K')
summary(emmeans(lme2,pairwise~Insecticide,mode='k')$contrast,infer=T)

```


# simple effects as replicates
```{r,fig.width=10,fig.Biomass=4}
library(emmeans)
effects = as.data.frame(summary(rbind(emmeans(lme2,revpairwise~Insecticide|Block)$contrast)))
estimates = as.data.frame(summary(emmeans(lme2,~Insecticide:Block)))
p1 = ggplot(estimates,aes(x=Insecticide,y=emmean)) + geom_line(aes(group = Block)) + ylab('Block mean')
p2 = ggplot(effects,aes(x=estimate)) + geom_histogram(breaks = seq(-60,10,by=2),fill='grey90',col=1) + xlab(expression(delta[i]))
plot_grid(p1,p2)
```

## Average G:T
```{r}
mean_data = aggregate(Biomass~Block+Insecticide+Pot,data,FUN=mean)
anova(lm(Biomass ~ Block * Insecticide,mean_data))
```


## Mixed effect anova
```{r}
library(lmerTest)
library(pbkrtest)
lme2 = lmer(Biomass ~ Insecticide + Block + Block:Insecticide + (1|Pot),data)
anova(lme2,ddf='K')
```

```{r}
anova(lme1,ddf='K')
```

## compare to t-test of effects
```{r}
t.test(effects$estimate)
```


## trt effects
```{r}
summary(emmeans(lme1,pairwise~Insecticide)$contrast)
```

```{r}
summary(emmeans(lme2,pairwise~Insecticide)$contrast)
```