---
title: "Class 9"
output: html_notebook
---

```{r}
library(lme4)
library(emmeans)
library(lmerTest)
library(ggplot2)
library(splines)
```



```{r}
alpine_potato = read.csv('Alpine_Russet_yield.csv')
ggplot(alpine_potato,aes(x=Nitrogen,y=Yield,group = Nitrogen)) + geom_boxplot(color = 'blue',position = position_identity()) + ggtitle('Alpine Russet')+
    scale_x_continuous(breaks = unique(alpine_potato$Nitrogen)) + expand_limits(y=0)
```

```{r}
model_reg4 = lm(Yield ~ Nitrogen + I(Nitrogen^2) + I(Nitrogen^3) + I(Nitrogen^4),alpine_potato)
anova(model_reg4)
```

```{r}
model_reg2 = lm(Yield ~ Nitrogen + I(Nitrogen^2),alpine_potato)
Nitrogen_scale = seq(0,300,length=100)
alpine_model_fit = data.frame(Nitrogen = Nitrogen_scale)

reg2_means = as.data.frame(emmeans(model_reg2,specs = 'Nitrogen',at=list(Nitrogen = alpine_model_fit$Nitrogen)))
alpine_model_fit$reg2 = reg2_means$emmean
alpine_model_fit$reg2_m2SE = reg2_means$lower.CL
alpine_model_fit$reg2_p2SE = reg2_means$upper.CL
p1 = ggplot(alpine_potato,aes(x=Nitrogen)) +
    scale_x_continuous(breaks = unique(alpine_potato$Nitrogen))+ 
    geom_boxplot(aes(y=Yield,group = Nitrogen),color = 'blue',position = position_identity()) + ggtitle('Alpine Russet') + 
    geom_ribbon(data = alpine_model_fit,aes(ymin = reg2_m2SE,ymax = reg2_p2SE),alpha = 0.3) + 
    geom_line(data=alpine_model_fit,aes(y=reg2),size=2,color='red')

p1
```


```{r}
alpine_potato$NitrogenFactor = factor(alpine_potato$Nitrogen)
model_unrep2 = lmer(Yield ~ Nitrogen + I(Nitrogen^2) + (1|NitrogenFactor),alpine_potato)
anova(model_unrep2,type='I',lmer.df = 'K')
```

```{r}
anova(model_reg2)
```


```{r,fig.width=10,fig.height=4}
unrep_reg2_means = as.data.frame(emmeans(model_unrep2,specs = 'Nitrogen',at=list(Nitrogen = alpine_model_fit$Nitrogen)))
alpine_model_fit$unrep_reg2 = unrep_reg2_means$emmean
alpine_model_fit$unrep_reg2_m2SE = unrep_reg2_means$lower.CL
alpine_model_fit$unrep_reg2_p2SE = unrep_reg2_means$upper.CL
p2 = ggplot(alpine_potato,aes(x=Nitrogen)) +
    scale_x_continuous(breaks = unique(alpine_potato$Nitrogen))+ 
    geom_boxplot(aes(y=Yield,group = Nitrogen),color = 'blue',position = position_identity()) + ggtitle('Unreplicated') + 
    geom_ribbon(data = alpine_model_fit,aes(ymin = unrep_reg2_m2SE,ymax = unrep_reg2_p2SE),alpha = 0.3) + 
    geom_line(data=alpine_model_fit,aes(y=unrep_reg2),size=2,color='red')

cowplot::plot_grid(p1,p2)
```
