---
title: "R Notebook"
runtime: shiny
output: html_notebook
---

# 
```{r echo = F}
library(ggplot2)
nG = 3
nR = 4
s_trt = 2
s_res = 1.5
width = .15
set_data = function(nG,nR) {
  sim_data = data.frame(Treatment = gl(nG,nR),Rep = 1:nR)
  sim_data$Treatment2 = factor(as.numeric(sim_data$Treatment) %% 6 + 1)
  sim_data$x = as.numeric(sim_data$Treatment) + width*2*((sim_data$Rep - mean(1:nR))/(nR-1)) 
  trt = rnorm(nG,0,s_trt) + 5 + (1:nG)/2 - (1:nG)^2/5
  sim_data$y = trt[sim_data$Treatment] + rnorm(nG*nR,0,s_res)
  sim_data$X= as.numeric(sim_data$Treatment)
  Xstd = poly(sim_data$X,min(nG,1))
  colnames(Xstd) = c('X1','X2')[1:ncol(Xstd)]
  sim_data = cbind(sim_data,Xstd)
  
  trt_data = subset(sim_data,Rep==1)
  trt_data$x = as.numeric(trt_data$Treatment)
  sim_data <<- sim_data
  trt_data <<- trt_data
}
set_data(nG,nR)

full_model = formula(y~Treatment)

```

```{r echo = F}
n_terms = 2
plot_model = function(data,full_model,n_terms,models){
  X = model.matrix(full_model)
  X_trt = subset(X,data$Rep == 1)
  coefs = tapply(coef(full_model),full_model$assign,function(x) x)
  
  p = ggplot() + geom_hline(yintercept = 0) +  expand_limits(y=min(0,min(data$y)))#ylim(mean(data$y) + 1.5*c(-1,1)*diff(range(data$y))/2) +
  p = p + scale_x_continuous(breaks = unique(trt_data$x),labels = unique(data$Treatment))
  
  # zero line
  coefs_set = 0
  data$predicted = 0
  trt_data$predicted = 0
  col = 1
  size = 1
  if(n_terms == 0){
    col = 'red'
    size = 2
    p = p + geom_line(data = data,aes(x=x,y=predicted),col=col,size=size)
  } else{
    p = p + geom_line(data = data,aes(x=x,y=predicted,group = Treatment),col=col,size=size)
  }
  data$last_predicted = data$predicted
  trt_data$last_predicted = trt_data$predicted
  
  arrows = c()
  if(n_terms > 0){
    n_coefs = pmin(length(coefs),n_terms)
    for(t in 1:n_coefs){
      coefs_set = unlist(coefs[1:t])
      # new_coefs = coef(lm(full_model$model$y~0+X[,1:length(coefs_set),drop=F]))
      # data$predicted = X[,1:length(coefs_set),drop=F] %*% new_coefs
      # trt_data$predicted = X_trt[,1:length(coefs_set),drop=F] %*% new_coefs
      new_coefs = rep(0,ncol(X))
      new_coefs[1:length(coefs_set)] = coefs_set
      data$predicted = X %*% new_coefs
      trt_data$predicted = X_trt %*% new_coefs
      if(n_coefs == 1 && var(trt_data$predicted) == 0) {
        p = p + geom_line(data = data,aes(x=x,y=predicted),color=n_coefs - t+2,size=1.5)
      } else if(t == 1  && var(trt_data$predicted) == 0){
        p = p + geom_line(data = data,aes(x=x,y=predicted),color=1)
      }
      col = 1
      size = 1
      if(t == n_coefs){
        col = 'red'
        size = 2
      }
      p = p + geom_line(data = data,aes(x=x,y=predicted,group = Treatment),color=col,size = size)
      trt_data$x_pos = trt_data$x + .02*(t-1)
      sub_trt = subset(trt_data,abs(predicted - last_predicted) > 0)
      arrows = rbind(arrows,data.frame(sub_trt,Parameter = t))
      # p = p + geom_segment(data = sub_trt,aes(x    = x_pos,y=last_predicted,
      #                                          xend = x_pos,yend = predicted,
      #                                          group = Treatment),
      #                                       arrow = arrow(length = unit(0.03,'npc')),color=n_coefs - t+2)
      data$last_predicted = data$predicted
      trt_data$last_predicted = trt_data$predicted
    }
    
  }
  
  if(n_terms >= 0) {
    # p = p + geom_segment(data = data,aes(x=x,y=predicted,xend = x, yend = y),arrow = arrow(length = unit(0.03,'npc')),color = 1,size=1.5) 
    error_arrows = data
    error_arrows$x_pos = error_arrows$x
    error_arrows$last_predicted = error_arrows$predicted
    error_arrows$predicted = error_arrows$y
    error_arrows$Parameter = 0
    if(length(arrows) > 0) {
      arrows = rbind(do.call(data.frame,arrows),error_arrows)
    } else{
      arrows = error_arrows
    }
    arrows$Parameter = factor(arrows$Parameter)
    levels(arrows$Parameter)[1] = expression(e[ij])
    p = p + geom_segment(data = arrows,aes(x    = x_pos,y=last_predicted,
                                         xend = x_pos,yend = predicted,
                                         group = Treatment,color = Parameter),
                                      arrow = arrow(length = unit(0.03,'npc')),size=1)
  }
  
  p = p + geom_point(data = data,aes(x=x,y=y,shape = Treatment2),size=4)
  
  if(any(grepl('X',full_model$call)) || any(grepl('model',full_model$call))) {
    dataX = data.frame(X = seq(min(data$x),max(data$x),length=100))
    dataX$y = 0
    if(n_terms ==1 ){
      dataX$y = predict(lm(y~1,data),newdata = dataX)
    } else if(n_terms == 2 ){
      dataX$y = predict(lm(y~X,data),newdata = dataX)
    } else if(n_terms > 2){
      dataX$y = predict(lm(y~poly(X,n_terms-1),data),newdata = dataX)
    }
    # Xstd = predict(poly(data$X,n_terms-1),dataX$X)
    # dataX$X1 = Xstd[,1]
    # dataX$X2 = Xstd[,2]
    # dataX$y = 0
    # if(length(coefs_set)>0) {
    # dataX$y = model.matrix(formula(full_model$call$formula),dataX)[,1:length(coefs_set),drop=F] %*% coefs_set
      # predict(full_model,newdata = dataX)
    # }

    p = p + geom_line(data = dataX,aes(x=X,y=y),col=2,size=2)
  }
  model = models[n_terms+1]
  if(length(model) == 0) model = expression(y[ij])
  if(n_terms < 0){
    SSE = ''
  } else{
    SSE = sprintf('%0.2f',sum((data$predicted - data$y)^2))
  }
  p + labs(title = model,subtitle = sprintf('SSE: %s',SSE)) + #/(nR*(nG-1))
    theme(plot.title = element_text(size = 30),plot.subtitle = element_text(size=30), axis.text=element_text(size=20)) + 
    ylim(c(min(0,1.1*min(data$y)),1.1*max(data$y))) 
}
```

```{r echo = F}
options(contrasts = c('contr.treatment','contr.poly'))
nG = length(unique(sim_data$Treatment))
model_names = list('lm(Y~Treatment,contrasts = list(Treatment = contr.sum)' = 'effect',
              'lm(Y~Treatment)' = 'trt_vs_control',
              'lm(Y~0+Treatment)' = 'means',
              'lm(Y~poly(X,2))' = 'regression_full'
              # 'lm(Y~A+B+A:B)' = 'interaction1',
              # 'lm(Y~A+B+A:B,contrasts = list(A=contr.sum,B=contr.sum))' = 'interaction2'
              )
selectInput('model','Model',model_names,width='1000px')
inputPanel(
  actionButton('addTerm','add Term'),
  actionButton('dropTerm','drop Term'),
  actionButton('reset','Reset'),
  actionButton('addGroup','Add group'),
  actionButton('dropGroup','Remove group')
)
## new data
status = 0
reactive({
  input$addGroup
  nG <<- min(8,nG + 1)
})
reactive({
  input$dropGroup
  nG <<- max(2,nG - 1)
})
reactive({
  input$addGroup
  input$dropGroup
  if(input$reset > status || nG != length(unique(sim_data$Treatment))) {
    # trt = rnorm(nG,0,s_trt)
    # data$y = trt[data$Treatment] + rnorm(nG,0,s_res)
    set_data(nG,nR)
    status <<- input$reset
    reg_model = sprintf('lm(y~poly(X,%d))',nG-1)
    # print(names(models))
    names(model_names)[4] <<- reg_model
    # print(model_names)
    updateSelectInput(session,inputId = 'model',label = 'Model',choices = model_names,selected = input$model)
    n_terms <<- -1
  }
})

## select model set
n_terms = -1
reactive({
  input$addGroup
  input$dropGroup
  input$reset
  if(input$model == 'effect'){
    full_model <<- lm(y ~ 1+Treatment,sim_data,contrast = list(Treatment = contr.sum))
    models <<- c(expression(paste(y[ij],'=',e[ij])),expression(paste(y[ij],'=',mu+e[ij])),expression(paste(y[ij],'=',mu+tau[i]+e[ij],',  ',Sigma,tau[i],'=',0)))
    n_terms <<- min(n_terms,2)
  } else if(input$model == 'trt_vs_control'){
    full_model <<- lm(y ~ 1+Treatment,sim_data,contrast = list(Treatment = contr.treatment))
    models <<- c(expression(paste(y[ij],'=',e[ij])),expression(paste(y[ij],'=',mu[1]+e[ij])),expression(paste(y[ij],'=',mu[1]+delta[i]+e[ij],',  ',delta[1],'=',0)))
    n_terms <<- min(n_terms,2)
  } else if(input$model == 'means') {
    full_model <<- lm(y ~ 0+Treatment,sim_data)
    models <<- c(expression(paste(y[ij],'=',e[ij])),expression(paste(y[ij],'=',mu[i]+e[ij])))
    n_terms <<- min(n_terms,1)
  } else if(input$model == 'regression_full') {
    model = 'y~1'
    if(nG > 1) {
      # eqn = ''
      # for(i in 1:nG){
      #   eqn = paste(eqn,sprintf('+I(X^%d)',i))
      # }
      # model = formula(paste(model,eqn))
      model = formula(paste(model,paste(sprintf('+poly(X,nG-1)[,%d]',1:(nG-1)),collapse='')))
    }
    full_model <<- lm(model,sim_data)
    models <<- c(expression(paste(y[ij],'=',e[ij])),
                 expression(paste(y[ij],'=',mu+e[ij])),
                 expression(paste(y[ij],'=',b[0],'+',paste(b[1],X[i]),'+',e[ij])),
                 expression(paste(y[ij],'=',b[0],'+',paste(b[1],X[i]),'+',paste(b[2],X[i]^2),'+',e[ij])),
                 expression(paste(y[ij],'=',b[0],'+',paste(b[1],X[i]),'+',paste(b[2],X[i]^2),'+',paste(b[3],X[i]^3),'+',e[ij])),
                 expression(paste(y[ij],'=',b[0],'+',paste(b[1],X[i]),'+',paste(b[2],X[i]^2),'+',paste(b[3],X[i]^3),'+',paste(b[4],X[i]^4),'+',e[ij])),
                 expression(paste(y[ij],'=',b[0],'+',paste(b[1],X[i]),'+',paste(b[2],X[i]^2),'+',paste(b[3],X[i]^3),'+',paste(b[4],X[i]^4),'+',paste(b[5],X[i]^5),'+',e[ij])),
                 expression(paste(y[ij],'=',b[0],'+',paste(b[1],X[i]),'+',paste(b[2],X[i]^2),'+',paste(b[3],X[i]^3),'+',paste(b[4],X[i]^4),'+',paste(b[5],X[i]^5),'+',paste(b[6],X[i]^6),'+',e[ij])),
                 expression(paste(y[ij],'=',mu,'+',paste(b[1],X[i]),'+',paste(b[2],X[i]^2),'+',paste(b[3],X[i]^3),'+',paste(b[4],X[i]^4),'+',paste(b[5],X[i]^5),'+',paste(b[6],X[i]^6),'+',paste(b[7],X[i]^7),'+',e[ij])))
    models <<- models[1:(nG+1)]
    n_terms <<- min(n_terms,nG)
  } else if(input$model == 'interaction1') {
    if(!grepl('A',sim_data$Treatment)) {
      sim_data$A = factor(c('a','A')[(as.numeric(sim_data$Treatment) %% 2 == 1)+1])
      sim_data$B = factor(c('b','B')[(as.numeric(sim_data$Treatment) < mean(as.numeric(levels(sim_data$Treatment))))+1])
      sim_data$Treatment = with(sim_data,paste(A,B,sep=':'))
    }
    full_model <<- lm(y~A + B + A:B,sim_data)
    models <<- c(expression(paste(y[ij],'=',e[ij])),
                 expression(paste(y[ij],'=',mu+e[ij])),
                 expression(paste(y[ij],'=',mu+a[i]+e[ij])),
                 expression(paste(y[ij],'=',mu+a[i]+b[j]+e[ij])),
                 expression(paste(y[ij],'=',mu+a[i]+b[j]+ab[ij]+e[ij])))
    n_terms <<- min(n_terms,4)
  } else if(input$model == 'interaction2') {
    if(!grepl('A',sim_data$Treatment)) {
      sim_data$A = c('a','A')[(as.numeric(sim_data$Treatment) %% 2 == 1)+1]
      sim_data$B = c('b','B')[(as.numeric(sim_data$Treatment) < mean(as.numeric(levels(sim_data$Treatment))))+1]
      sim_data$Treatment = with(sim_data,paste(A,B,sep=':'))
    }
    full_model <<- lm(y~A + B + A:B,sim_data,contrasts = list(A=contr.sum,B=contr.sum))
    models <<- c(expression(paste(y[ij],'=',e[ij])),
                 expression(paste(y[ij],'=',mu+e[ij])),
                 expression(paste(y[ij],'=',mu+a[i]+e[ij])),
                 expression(paste(y[ij],'=',mu+a[i]+b[j]+e[ij])),
                 expression(paste(y[ij],'=',mu+a[i]+b[j]+ab[ij]+e[ij])))
    n_terms <<- min(n_terms,4)
  }
  # only set n_terms if this is the first time
  # if(status == 0)  n_terms <<- length(models)-1
})

## select n_terms
reactive({
  if(input$addTerm > 0) {
    n_terms <<- min(length(models)-1,n_terms+1)
  }
})
reactive({
  if(input$dropTerm > 0) {
    n_terms <<- max(-1,n_terms-1)
  }
})
renderPlot({
  input$addGroup
  input$dropGroup
  input$addTerm
  input$dropTerm
  input$model
  input$reset
  plot_model(sim_data,full_model,n_terms,models)
},height=500)
reactive({
  input$addGroup
  input$dropGroup
  input$addTerm
  input$dropTerm
  input$model
  input$reset
  print(anova(full_model))
})
```

