---
title: "Class 8"
output: html_notebook
---
## 
```{r}
library(ggplot2)
library(cowplot)
library(emmeans)
potato_reps = read.csv('Potato_yield.csv')
potato_reps$NitrogenF = as.factor(potato_reps$Nitrogen)
potato_reps$Variety = factor(potato_reps$Variety,labels = c('Alpine','Burbank'))
```
```{r}
ggplot(subset(potato_reps,Variety == 'Alpine'),aes(x=Nitrogen,y=Yield,group = interaction(Nitrogen))) + geom_boxplot() + 
    scale_x_continuous(breaks = unique(potato_reps$Nitrogen))
```

```{r}
ggplot(potato_reps,aes(x=Nitrogen,y=Yield,group = interaction(Nitrogen,Variety))) + geom_boxplot(aes(color = Variety,fill=NULL),position = position_dodge(width=5)) + 
    scale_x_continuous(breaks = unique(potato_reps$Nitrogen))
```


## Interactions

```{r,fig.width=10,fig.height = 4}
p_low=ggplot(subset(potato_reps,Nitrogen %in% c(0,90)),aes(x=factor(Nitrogen),y=Yield,group = interaction(Nitrogen,Variety))) + geom_boxplot(aes(color = Variety,fill=NULL),position = position_dodge(width=.5))
p_high = ggplot(subset(potato_reps,Nitrogen %in% c(210,270)),aes(x=factor(Nitrogen),y=Yield,group = interaction(Nitrogen,Variety))) + geom_boxplot(aes(color = Variety,fill=NULL),position = position_dodge(width=.5))
plot_grid(p_low,p_high)                       
```
```{r}
summary(emmeans(lm(Yield ~ NitrogenF:Variety,subset(potato_reps,Nitrogen %in% c(0,90))),~Variety:NitrogenF),infer=F)
summary(emmeans(lm(Yield ~ NitrogenF:Variety,subset(potato_reps,Nitrogen %in% c(210,270))),~Variety:NitrogenF),infer=F)
```
```{r}
summary(rbind(emmeans(lm(Yield ~ NitrogenF:Variety,subset(potato_reps,Nitrogen %in% c(0,90))),pairwise~Variety|NitrogenF)$contrasts),infer=F)
summary(rbind(emmeans(lm(Yield ~ NitrogenF:Variety,subset(potato_reps,Nitrogen %in% c(210,270))),pairwise~Variety|NitrogenF)$contrasts),infer=F)
```
```{r}
summary(pairs(rbind(emmeans(lm(Yield ~ NitrogenF:Variety,subset(potato_reps,Nitrogen %in% c(0,90))),pairwise~Variety|NitrogenF)$contrasts)))
summary(pairs(rbind(emmeans(lm(Yield ~ NitrogenF:Variety,subset(potato_reps,Nitrogen %in% c(210,270))),pairwise~Variety|NitrogenF)$contrasts)))
```

```{r,fig.width=10,fig.height = 4}
p_low=ggplot(subset(potato_reps,Nitrogen %in% c(0,90)),aes(x=factor(Nitrogen),y=Yield)) + geom_smooth(aes(x=Nitrogen,color = Variety),method='lm',se=F)
p_high = ggplot(subset(potato_reps,Nitrogen %in% c(210,270)),aes(x=factor(Nitrogen),y=Yield)) + geom_smooth(aes(x=Nitrogen,color = Variety),method='lm',se=F)
plot_grid(p_low,p_high)                       
```

```{r}
potato_model = lm(Yield ~ NitrogenF * Variety,potato_reps)
potato_estimates = as.data.frame(summary(emmeans(potato_model,~NitrogenF:Variety),infer = T))
potato_estimates$Nitrogen = as.numeric(as.character(potato_estimates$NitrogenF))
ggplot(potato_estimates,aes(x=Nitrogen,y=emmean)) + geom_line(aes(color = Variety)) + ylab('Yield')
```

## ANOVA table
```{r}
full_model = lm(Yield ~ Variety + NitrogenF + Variety:NitrogenF, potato_reps)
anova(full_model)
```

## Nitrogen effects for each Variety
```{r}
summary(emmeans(lm(Yield ~ NitrogenF:Variety,subset(potato_reps,Nitrogen %in% c(0,90))),~NitrogenF:Variety),infer=F)
summary(emmeans(lm(Yield ~ NitrogenF:Variety,subset(potato_reps,Nitrogen %in% c(210,270))),~NitrogenF:Variety),infer=F)
```

```{r,fig.width=10,fig.height = 4}
p_N=ggplot(subset(potato_reps,Nitrogen %in% c(0,90)),aes(x=factor(Nitrogen),y=Yield)) + geom_smooth(aes(x=Nitrogen,color = Variety),method='lm',se=F)
p_V=ggplot(subset(potato_reps,Nitrogen %in% c(0,90)),aes(x=Variety,y=Yield,group = factor(Nitrogen))) + geom_smooth(aes(x=Variety,color = factor(Nitrogen)),method='lm',se=F)
plot_grid(p_N,p_V)                       
```
```{r,fig.width=10,fig.height = 4}
p_N=ggplot(subset(potato_reps,Nitrogen %in% c(210,270)),aes(x=factor(Nitrogen),y=Yield)) + geom_smooth(aes(x=Nitrogen,color = Variety),method='lm',se=F)
p_V=ggplot(subset(potato_reps,Nitrogen %in% c(210,270)),aes(x=Variety,y=Yield,group = factor(Nitrogen))) + geom_smooth(aes(x=Variety,color = factor(Nitrogen)),method='lm',se=F)
plot_grid(p_N,p_V)                       
```


```

