---
title: "Class 4"
output: html_notebook
---

## Load the pulse data
```{r echo = F}
pulse_data <- read.csv('Pulse experiment response.csv')
colnames(pulse_data)[3] = 'Pulse'
```

## Plot data
```{r,fig.width=4,fig.height=5}
set.seed(1)
library(ggplot2)
ggplot(pulse_data,aes(x=Posture,y=Pulse)) + geom_jitter(size=2,width = .1,alpha = 0.5)
```

## Statistics
```{r}
standing_obs = subset(pulse_data,Posture == 'Standing')$Pulse
sitting_obs = subset(pulse_data,Posture == 'Sitting')$Pulse
length(standing_obs)
length(sitting_obs)
mean(standing_obs)
mean(sitting_obs)
var(standing_obs)
var(sitting_obs)
```

```{r}
pooled_s2 = ((length(sitting_obs)-1)*var(sitting_obs) + (length(standing_obs)-1)*var(standing_obs))/(nrow(pulse_data)-2)
pooled_s2
```

```{r}
sqrt(252/36+262/38)
```


## delta
```{r}
ybar_1 = mean(standing_obs)
ybar_2 = mean(sitting_obs)
delta = ybar_1 - ybar_2
delta
```

## SED
```{r}
n1 = sum(pulse_data$Posture == 'Standing')
n2 = sum(pulse_data$Posture == 'Sitting')
s2_1 = var(standing_obs)
s2_2 = var(sitting_obs)

# pooled estimate of population variance (assuming both pops have same variance)
# pooling counts each individual equally
s2 = ((n1-1)*s2_1 + (n2-1)*s2_2)/(n1+n2-2)

# use pooled s2 to estimate SED
SED = sqrt(s2/n1 + s2/n2)
SED
```

## t statistic
```{r}
t_hat = delta / SED
t_hat
```

## null distribution of values if H0 is true
```{r}
possible_ts = rt(10000,df=n1-1 + n2-1)  # degrees of freedom = (sitting's df + standing's df)
hist(possible_ts,breaks=100)
hist(possible_ts,breaks=100)
abline(v=c(-1,1)*t_hat) # mark our t_hat from the data
hist(possible_ts[abs(possible_ts) > t_hat],breaks=100,add=T,col=2) # color all those possible t's greater than our observed
```

## p-value
Fraction of null distribution of normalized errors greater than our observed
```{r}
mean(abs(possible_ts) > t_hat)
```

## calculate using pt
```{r}
2 * pt(t_hat,df = (n1-1)+(n2-1),lower.tail = FALSE)
```

