---
title: "Class 6"
output: html_notebook
---
## 
```{r}
library(ggplot2)
library(cowplot)
library(lsmeans)
```


```{r}
alpine_potato = read.csv('Alpine_Russet_yield.csv')
ggplot(alpine_potato,aes(x=Nitrogen,y=Yield,group = Nitrogen)) + geom_boxplot(color = 'blue',position = position_identity()) + ggtitle('Alpine Russet')+
    scale_x_continuous(breaks = unique(alpine_potato$Nitrogen)) + expand_limits(y=0)
```

## Trends:
```{r}
model_reg4 = lm(Yield ~ Nitrogen + I(Nitrogen^2) + I(Nitrogen^3) + I(Nitrogen^4),alpine_potato)
anova(model_reg4)
anova(lm(Yield ~ factor(Nitrogen),alpine_potato))
```

```{r}
library(reshape)
model_reg4 = lm(Yield ~ poly(Nitrogen,degree = 4),alpine_potato)
model_reg3 = lm(Yield ~ poly(Nitrogen,degree = 3),alpine_potato)
model_reg2 = lm(Yield ~ poly(Nitrogen,degree = 2),alpine_potato)
model_reg1 = lm(Yield ~ poly(Nitrogen,degree = 1),alpine_potato)
Nitrogen_scale = seq(0,300,length=100)
alpine_model_fit = data.frame(Nitrogen = Nitrogen_scale)
alpine_model_fit$reg4 = predict(model_reg4,newdata = alpine_model_fit)
alpine_model_fit$reg3 = predict(model_reg3,newdata = alpine_model_fit)
alpine_model_fit$reg2 = predict(model_reg2,newdata = alpine_model_fit)
alpine_model_fit$reg1 = predict(model_reg1,newdata = alpine_model_fit)
alpine_model_fit = melt(alpine_model_fit,id.vars = 'Nitrogen')
ggplot(alpine_potato,aes(x=Nitrogen,y=Yield)) + geom_boxplot(aes(group = Nitrogen),color = 'blue',position = position_identity()) + ggtitle('Alpine Russet')+
    scale_x_continuous(breaks = unique(alpine_potato$Nitrogen)) + 
    geom_line(data=alpine_model_fit,aes(y=value,color = variable),size=2)
```


```{r,fig.width=10,fig.height=4}
model_reg2 = lm(Yield ~ poly(Nitrogen,degree = 2),alpine_potato)
Nitrogen_scale = seq(0,300,length=100)
alpine_model_fit = data.frame(Nitrogen = Nitrogen_scale)
reg4_means = as.data.frame(emmeans(model_reg4,specs = 'Nitrogen',at=list(Nitrogen = alpine_model_fit$Nitrogen)))
alpine_model_fit$reg4 = reg4_means$emmean
alpine_model_fit$reg4_m2SE = reg4_means$lower.CL
alpine_model_fit$reg4_p2SE = reg4_means$upper.CL
p1 = ggplot(alpine_potato,aes(x=Nitrogen)) +
    scale_x_continuous(breaks = unique(alpine_potato$Nitrogen))+ 
    geom_boxplot(aes(y=Yield,group = Nitrogen),color = 'blue',position = position_identity()) + ggtitle('Alpine Russet') + 
    geom_ribbon(data = alpine_model_fit,aes(ymin = reg4_m2SE,ymax = reg4_p2SE),alpha = 0.3) + 
    geom_line(data=alpine_model_fit,aes(y=reg4),size=2,color='red')

reg2_means = as.data.frame(emmeans(model_reg2,specs = 'Nitrogen',at=list(Nitrogen = alpine_model_fit$Nitrogen)))
alpine_model_fit$reg2 = reg2_means$emmean
alpine_model_fit$reg2_m2SE = reg2_means$lower.CL
alpine_model_fit$reg2_p2SE = reg2_means$upper.CL
p2 = ggplot(alpine_potato,aes(x=Nitrogen)) +
    scale_x_continuous(breaks = unique(alpine_potato$Nitrogen))+ 
    geom_boxplot(aes(y=Yield,group = Nitrogen),color = 'blue',position = position_identity()) + ggtitle('Alpine Russet') + 
    geom_ribbon(data = alpine_model_fit,aes(ymin = reg2_m2SE,ymax = reg2_p2SE),alpha = 0.3) + 
    geom_line(data=alpine_model_fit,aes(y=reg2),size=2,color='red')

plot_grid(p1,p2)
```

